In [1]:
import torch

model_names = ['yolov5l']#, 'yolov5x']

# Model
models = {x[-1]:torch.hub.load('ultralytics/yolov5', x, force_reload=True) for x in model_names}  # or yolov5n - yolov5x6, custom

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = models['n'](img)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.

/Users/mmacchini/opt/anaconda3/envs/objdet/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /Users/mmacchini/.cache/torch/hub/master.zip
YOLOv5 🚀 2022-6-1 Python-3.9.12 torch-1.11.0 CPU

Fusing layers... 
YOLOv5l summary: 367 layers, 46533693 parameters, 0 gradients
Adding AutoShape... 


KeyError: 'n'

In [3]:
model = torch.hub.load('ultralytics/yolov5', 'yolov5l')
modeln = torch.hub.load('ultralytics/yolov5', 'yolov5n')


Using cache found in /Users/mmacchini/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2022-6-1 Python-3.9.12 torch-1.11.0 CPU

Fusing layers... 
YOLOv5l summary: 367 layers, 46533693 parameters, 0 gradients
Adding AutoShape... 
Using cache found in /Users/mmacchini/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2022-6-1 Python-3.9.12 torch-1.11.0 CPU

Fusing layers... 
YOLOv5n summary: 213 layers, 1867405 parameters, 0 gradients
Adding AutoShape... 


In [4]:
import time
import glob

# img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list
# img = '/Users/mmacchini/Downloads/IMG_5284.png'
# img = '/Users/mmacchini/Desktop/Screenshots/Screen Shot 2022-05-16 at 11.43.23 AM.png'
img = 'https://www.cherry.fr/media/wysiwyg/hero_product_content/CHERRY_STREAM_HERO_1_900.jpg'
# img = '/Users/mmacchini/Desktop/img_laptop.jpeg'
# img = 'https://i1.wp.com/www.alphr.com/wp-content/uploads/2017/02/macbook-keyboard-typing.jpg?fit=1280%2C720&ssl=1'
# Inference

imgs = glob.glob('/Users/mmacchini/Documents/data/typing_samples/*')

for img in imgs:
    t = time.time()
    results = model(img)
    print(f'took {time.time() - t}s')

    # Results
    results.show()  # or .print(), .save(), .crop(), .pandas(), etc.

took 1.434638261795044s
took 1.564964771270752s
took 1.784696102142334s
took 2.071303129196167s
took 1.345893144607544s
took 1.3952081203460693s
took 1.744352102279663s
took 1.8496348857879639s
took 1.5358788967132568s
took 1.4220657348632812s
took 1.5026919841766357s
took 1.82830810546875s


KeyboardInterrupt: 

In [12]:
import time
import glob

# img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list
# img = '/Users/mmacchini/Downloads/IMG_5284.png'
# img = '/Users/mmacchini/Desktop/Screenshots/Screen Shot 2022-05-16 at 11.43.23 AM.png'
img = 'https://www.cherry.fr/media/wysiwyg/hero_product_content/CHERRY_STREAM_HERO_1_900.jpg'
# img = '/Users/mmacchini/Desktop/img_laptop.jpeg'
# img = 'https://i1.wp.com/www.alphr.com/wp-content/uploads/2017/02/macbook-keyboard-typing.jpg?fit=1280%2C720&ssl=1'
# Inference

imgs = glob.glob('/Users/mmacchini/Documents/data/typing_samples/*')

for img in imgs:
    t = time.time()
    results = modeln(img)
    print(f'took {time.time() - t}s')

    # Results
    results.show()  # or .print(), .save(), .crop(), .pandas(), etc.

took 0.23591876029968262s
took 0.47904205322265625s
took 0.20958209037780762s
took 0.23043203353881836s
took 0.2722928524017334s
took 0.3032808303833008s
took 0.1853029727935791s
took 0.18308210372924805s
took 0.16033387184143066s
took 0.2820568084716797s
took 0.19318819046020508s
took 0.19693708419799805s
took 0.1549088954925537s


In [10]:
import time

# img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list
# img = '/Users/mmacchini/Downloads/IMG_5284.png'
# img = '/Users/mmacchini/Desktop/Screenshots/Screen Shot 2022-05-16 at 11.43.23 AM.png'
img = 'https://www.cherry.fr/media/wysiwyg/hero_product_content/CHERRY_STREAM_HERO_1_900.jpg'
# img = '/Users/mmacchini/Desktop/img_laptop.jpeg'
# img = 'data/images/object_detection_ex1_bw.jpg'
# Inference

for model in ['l']:
    t = time.time()
    results = models[model](img)
    print(f'took {time.time() - t}s')

    # Results
    results.show()  # or .print(), .save(), .crop(), .pandas(), etc.

took 1.7195460796356201s


In [24]:
data = results.pandas()

In [61]:
results.print()

image 1/1: 900x1920 2 persons, 1 mouse, 1 keyboard
Speed: 13604.6ms pre-process, 231.8ms inference, 1.9ms NMS per image at shape (1, 3, 320, 640)


In [62]:
results_nano.print()

image 1/1: 900x1920 2 persons, 1 mouse, 1 keyboard
Speed: 949.5ms pre-process, 130.0ms inference, 1.9ms NMS per image at shape (1, 3, 320, 640)


In [67]:
labels, cord_thres = results_nano.xyxyn[0][:, -1].numpy(), results_nano.xyxyn[0][:, :-1].numpy()

In [64]:
for i in range(len(labels)):
    print(results.names[int(labels[i])])
    print(cord_thres[i])

mouse
[    0.86397     0.36555     0.95977     0.69877     0.92529]
keyboard
[    0.19544     0.16251     0.83117     0.67429     0.84265]
person
[    0.55532     0.40764     0.73021     0.97674     0.47538]
person
[    0.21558     0.37573     0.75342           1     0.42283]


In [68]:
for i in range(len(labels)):
    print(results.names[int(labels[i])])
    print(cord_thres[i])

mouse
[    0.85951     0.37535     0.95868     0.69684     0.85636]
person
[    0.55477     0.41723     0.73194     0.98916     0.64223]
keyboard
[    0.18384     0.17329     0.77618     0.69814     0.50948]
person
[    0.24351     0.41451     0.41719     0.92323     0.48767]


In [53]:
results.show()

In [ ]:
nums = [4, 5, 9, 16, 32, 90, 91, 144, 256, 511, 1012, 1024]

fil = [x for x in nums if x>5]