In [1]:
import torch

model = torch.hub.load('.', 'custom', path='/Users/mmacchini/Documents/github/yolov5/pretrained/coco_subset_1_epoch/runs/train/exp/weights/best.pt', source='local')

# Images
img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list

# Inference
results = model(img)

# Results
results.show()  # or .show(), .save(), .crop(), .pandas(), etc.

/Users/mmacchini/opt/anaconda3/envs/objdet/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
YOLOv5 🚀 v6.1-221-gfc02981 Python-3.9.12 torch-1.11.0 CPU

Fusing layers... 
Model summary: 213 layers, 7029004 parameters, 0 gradients, 15.9 GFLOPs
Adding AutoShape... 


In [2]:

results = model(img)

# Results
results.show()  # or .show(), .save(), .crop(), .pandas(), etc.

In [5]:
import time
import glob

# img = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, PIL, OpenCV, numpy, list
# img = '/Users/mmacchini/Downloads/IMG_5284.png'
# img = '/Users/mmacchini/Desktop/Screenshots/Screen Shot 2022-05-16 at 11.43.23 AM.png'
img = 'https://www.cherry.fr/media/wysiwyg/hero_product_content/CHERRY_STREAM_HERO_1_900.jpg'
# img = '/Users/mmacchini/Desktop/img_laptop.jpeg'
# img = 'https://i1.wp.com/www.alphr.com/wp-content/uploads/2017/02/macbook-keyboard-typing.jpg?fit=1280%2C720&ssl=1'
# Inference

imgs = glob.glob('/Users/mmacchini/Documents/data/typing_samples/*')

for img in imgs:
    t = time.time()
    results = model(img)
    print(f'took {time.time() - t}s')

    # Results
    results.show()  # or .print(), .save(), .crop(), .pandas(), etc.

took 0.5599439144134521s
took 0.6200220584869385s
took 0.39482808113098145s
took 0.2826418876647949s
took 0.556304931640625s
took 0.5649161338806152s
took 0.3502068519592285s
took 0.5823581218719482s
took 0.2768421173095703s
took 0.5071091651916504s
took 0.3803870677947998s
took 0.6410210132598877s
took 0.35250401496887207s


In [24]:
data = results.pandas()

In [9]:
results.print()

image 1/1: 480x640 (no detections)
Speed: 25.8ms pre-process, 872.2ms inference, 0.8ms NMS per image at shape (1, 3, 480, 640)


In [10]:
results.print()

image 1/1: 480x640 (no detections)
Speed: 25.8ms pre-process, 872.2ms inference, 0.8ms NMS per image at shape (1, 3, 480, 640)


In [67]:
labels, cord_thres = results_nano.xyxyn[0][:, -1].numpy(), results_nano.xyxyn[0][:, :-1].numpy()

In [64]:
for i in range(len(labels)):
    print(results.names[int(labels[i])])
    print(cord_thres[i])

mouse
[    0.86397     0.36555     0.95977     0.69877     0.92529]
keyboard
[    0.19544     0.16251     0.83117     0.67429     0.84265]
person
[    0.55532     0.40764     0.73021     0.97674     0.47538]
person
[    0.21558     0.37573     0.75342           1     0.42283]


In [68]:
for i in range(len(labels)):
    print(results.names[int(labels[i])])
    print(cord_thres[i])

mouse
[    0.85951     0.37535     0.95868     0.69684     0.85636]
person
[    0.55477     0.41723     0.73194     0.98916     0.64223]
keyboard
[    0.18384     0.17329     0.77618     0.69814     0.50948]
person
[    0.24351     0.41451     0.41719     0.92323     0.48767]


In [53]:
results.show()

In [ ]:
nums = [4, 5, 9, 16, 32, 90, 91, 144, 256, 511, 1012, 1024]

fil = [x for x in nums if x>5]